package mc.webserver;

import lombok.Getter;

import javax.swing.*;
import java.awt.*;

/**
 * Created by sanjay on 20/01/2017.
 */
public class Console {
  @Getter
  private JTextArea textArea1;
  private JPanel jpanel;

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    jpanel = new JPanel();
    jpanel.setLayout(new GridBagLayout());
    textArea1 = new JTextArea();
    textArea1.setBackground(new Color(-16777216));
    textArea1.setForeground(new Color(-1));
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    gbc.fill = GridBagConstraints.BOTH;
    jpanel.add(textArea1, gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return jpanel;
  }
}
